### ISSUE TITLE
User-Defined Scan Interval

### ISSUE THREAD

**Issue by jdshutter** [nthallen/keutsch-hcho#5]
Would it be possible to allow the user to define the time interval between each scan (right in the program itself rather than needing to recompile)? At the moment, it's one minute, but it would be nice to sometimes make the interval longer (for instance, five or ten minutes).

- [X] Update algorithm
- [x] Document operating procedures (noting Time Warp option)
# For Test:
- [x] Verify operation

**Comment by nthallen** [comment]
This could be handled in a couple different ways.

1. We could make it universally configurable, defining the inter-scan period from the command line. This would require creating a TM variable for that setting and displaying and extracting it.
2. We could provide a few operating modes implementing different interscan periods, say 1, 5 and 10 minutes. This is simpler, since it does not involve additional data.

**Comment by jdshutter** [comment]
I think No. 2 is a much better option since the operator at most is only going to use one or two modes.

Inter-scan periods of 1, 5, 10 and 30 minutes should be way more than sufficient
